services:
  - type: web
    name: everyai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GIT_HUB_TOKEN
        sync: false
      - key: NVIDIA_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    autoDeploy: true
